---
- name: "print working directory"
  shell: |
    pwd
    ls -lh

- name: "Copy artifact.tar.gz to EC2"
  copy:
    src: "project/artifact.tar.gz"
    dest: "~/"

- name: "extract artifact"
  shell: |
    tar xzf artifact.tar.gz

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Stop Default
  shell: |
    pm2 stop default

- name: Start pm2 
  shell: |
    pm2 start npm -- start